# Generated by Django 3.1.2 on 2020-10-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.JSONField()),
                ('last_card', models.CharField(max_length=2, null=True)),
                ('active_player', models.IntegerField()),
                ('p1_code', models.CharField(max_length=255, null=True)),
                ('p2_code', models.CharField(max_length=255, null=True)),
                ('p1_name', models.CharField(max_length=255, null=True)),
                ('p2_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
